version: "3"
services:
    graph-node:
        image: graphprotocol/graph-node
        ports:
            - "8000:8000"
            - "8001:8001"
            - "8020:8020"
            - "8030:8030"
            - "8040:8040"
        depends_on:
            - ipfs
            - postgres

        environment:
            postgres_host: postgres
            postgres_user: graph-node
            postgres_pass: graph-pass
            postgres_db: graph-node
            ipfs: "ipfs:5001"
            ethereum: "avalanche:https://api.avax-test.network/ext/bc/C/rpc"
            GRAPH_LOG: debug
            GRAPH_ETHEREUM_CLEANUP_BLOCKS: "true"

    ipfs:
        image: ipfs/go-ipfs:v0.12.2
        environment:
            - IPFS_PROFILE=server
            - IPFS_PATH=/ipfsdata
        volumes:
            - ../../spark-nft-subgraph-data/ipfs:/ipfsdata
        ports:
            - "4001:4001"
            - "127.0.0.1:8080:8080"
            - "127.0.0.1:8081:8081"
            - "127.0.0.1:5001:5001"

    postgres:
        image: postgres:14.2
        ports:
            - "5432:5432"
        command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
        environment:
            POSTGRES_USER: graph-node
            POSTGRES_PASSWORD: graph-pass
            POSTGRES_DB: graph-node
        volumes:
            - ../../spark-nft-subgraph-data/postgres:/var/lib/postgresql/data
